version: 2.1

orbs:
  maven: circleci/maven@1.1

jobs:
  print_hello:
    docker:
      - image: circleci/java
    steps:
      - run: echo hello
  print_world:
    docker:
      - image: circleci/java
    steps:
      - run: echo  world
  build:
    docker:
      - image: circleci/alpine
    steps:
      - checkout
      - run:
          name: "echo an env variable"
          command: |
            echo $MY_ENV_VAR

workflows:
  maven_test:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
